# Generated by Django 5.2.16 on 2026-08-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Nombre de la persona o empresa que solicita el retiro', max_length=150)),
                ('referencia_interna', models.CharField(help_text='Código interno para identificar la orden', max_length=50, unique=True)),
                ('tipo_servicio', models.CharField(help_text='Tipo de servicio requerido (ej: retiro estándar, urgente, refrigerado)', max_length=100)),
                ('cantidad_bultos', models.PositiveIntegerField(help_text='Cantidad de bultos a retirar')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones libres sobre el pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
